version: '3.9'

services:
  backend:
    build:
      context: ./djchat
      dockerfile: Dockerfile
    image: backend-image
    container_name: backend-container
    # command: python manage.py runserver 0.0.0.0:8000
    command: uvicorn djchat.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --log-level debug --reload
    # command: sleep infinity
    volumes:
      - ./djchat:/home/src
    ports:
      - 8000:8000

# frontend => npm run dev